// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDyCtN4KYInCI8NXHKvYNVq4YPNk7e8o70",
      authDomain: "vmbs-2c700.firebaseapp.com",
      databaseURL: "https://vmbs-2c700-default-rtdb.firebaseio.com",
      projectId: "vmbs-2c700",
      storageBucket: "vmbs-2c700.appspot.com",
      messagingSenderId: "467918462056",
      appId: "1:467918462056:web:7478d83e2c7369189d2fdd",
      measurementId: "G-VXFMBV6G80");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyCtN4KYInCI8NXHKvYNVq4YPNk7e8o70',
    appId: '1:467918462056:web:7478d83e2c7369189d2fdd',
    messagingSenderId: '467918462056',
    projectId: 'vmbs-2c700',
    databaseURL: 'https://vmbs-2c700-default-rtdb.firebaseio.com',
    storageBucket: 'vmbs-2c700.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyDyCtN4KYInCI8NXHKvYNVq4YPNk7e8o70",
    appId: "1:467918462056:web:7478d83e2c7369189d2fdd",
    messagingSenderId: "467918462056",
    projectId: "vmbs-2c700",
    databaseURL: "https://vmbs-2c700-default-rtdb.firebaseio.com",
    storageBucket: "vmbs-2c700.appspot.com",
    androidClientId:
        '406099696497-17qn06u8a0dc717u8ul7s49ampk13lul.apps.googleusercontent.com',
    iosClientId:
        '406099696497-65v1b9ffv6sgfqngfjab5ol5qdikh2rm.apps.googleusercontent.com',
    iosBundleId: 'com.sanii.vehicleManagementAndBookingSystem',
  );
}
